# 7.2 Self Check

In [ ]:
import numpy as np

In [3]:
np.array([x for x in range(2, 21, 2)])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

# 7.3 Self Check

In [6]:
a = np.array([[2, 4, 6, 8, 10], [1, 3, 5, 7, 9]])

In [7]:
a.ndim

2

In [8]:
a.shape

(2, 5)

# 7.5 Self Check

In [ ]:
import numpy as np

In [9]:
np.arange(2, 41, 2).reshape(4, 5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

# 7.6 Self Check

In [ ]:
import numpy as np

In [10]:
%timeit sum([x for x in range(10_000_000)])

1.02 s ± 50.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
%timeit np.arange(10_000_000).sum()

24.4 ms ± 4.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 7.7 Self Check

In [ ]:
import numpy as np

In [12]:
np.arange(1, 6) ** 2

array([ 1,  4,  9, 16, 25])